language: node_js
node_js:
  - "0.10"
deploy:
  provider: s3
  access_key_id: $AWS_KEY_ID
  secret_access_key: $AWS_ACCESS_KEY
  bucket: instantmarkup.com
  endpoint: instantmarkup.com.s3-website-us-west-2.amazonaws.com
  region: us-west-2
  local_dir: public
  skip_cleanup: true
  acl: public_read
  on:
    repo: oliverzheng/instantmarkup.com
